"""
Add cascade delete
"""

from alembic import op
import sqlalchemy as sa
from alembic import context
import sqlalchemy.dialects.postgresql as pg

# revision identifiers, used by Alembic.
revision = '573fd07f9fe0'
down_revision = '89ffe4569ebc'
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('device_user_id_fkey'), 'device', type_='foreignkey')
    op.create_foreign_key(None, 'device', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_persona_id_fkey'), 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'persona', ['persona_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(op.f('user_persona_id_fkey'), 'user', 'persona', ['persona_id'], ['id'])
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.create_foreign_key(op.f('device_user_id_fkey'), 'device', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###